### ISSUE TITLE
Add default image if user doesn't have an image

### ISSUE THREAD

**Issue by ahmetws** [ahmetws/swifttube#16]
Some users don't have images. Add default image if it doesn't have an image in the home page and speakers page, search and conference detail.

Use https://pbs.twimg.com/profile_images/1080082434337722368/tVp-GkU6_400x400.jpg as default image

Check out Emre Kizildas as an example
http://www.swifttube.co/speaker/emre

**Comment by emrekizildas** [comment]
In your https://github.com/ahmetws/swifttube/blob/master/Resources/Views/speaker.leaf file, on avatar class maybe follow code fix that problem:
https://gist.github.com/emrekizildas/c29d95d7cbf98fe30ffa3e6a7672b085

**Comment by ahmetws** [comment]
Thanks @emrekizildas 👍
