### ISSUE TITLE
Add installation steps to Readme file

### ISSUE THREAD

**Issue by ahmetws** [ahmetws/swifttube#30]
It is hard for newcomers to understand how to install and run the project from the current Readme file. 
The project should have the installation steps as a section on the Readme file.

**Comment by b30wulffz** [comment]
Give me a demo of installation and I will do it.

**Comment by jstashh** [comment]
I was trying to do this last night because it’s quite easy but vapor update wouldn’t run. There was a problem with MongoKitten in the package.swift file. If you change it to from version 5.0.0 then it works but then you get like 60 errors because you MongoKitten has changed

**Comment by ahmetws** [comment]
I created a new issue to update MongoKitten. #31

**Comment by ahmetws** [comment]
Thanks @wstompearson 👍 It's updated now.

@b30wulffz You can install Vapor and run the app directly. It should work. Let us know if you need anything

**Comment by jstashh** [comment]
@b30wulffz I added the steps in /pull/34, so now there should be info on the readme. Happy to help if you have problems running it
