### ISSUE TITLE
Add upcoming badge to upcoming videos

### ISSUE THREAD

**Issue by ahmetws** [ahmetws/swifttube#39]
When listing the upcoming videos, the user should differentiate it between the normal videos. 
There should be a badge or a text on To mock ’to mock a mockingbird’ video in these pages.
http://www.swifttube.co/event/swiftfest2019
http://www.swifttube.co/speaker/danielsteinberg

Design can be an "Upcoming" text with the style of tags in the project but any creative idea would be very helpful.

**Comment by ahmetws** [comment]
It should also be applied to http://www.swifttube.co/videos page

**Comment by gsoykan** [comment]
I will be working on this
