### ISSUE TITLE
Project doesn't build

### ISSUE THREAD

**Issue by jstashh** [ahmetws/swifttube#51]
This might be specific to my machine but thought I would raise an issue about it.

I just did a fresh clone of the project and ran `vapor update`

If I run it and go to `localhost:8080` I get: 

```
{
    error: true,
    reason: "Something went wrong."
}
```

If I debug it and print out the error I get: 

```
(MongoKitten.MongoKittenError) $R0 = {
  kind = unableToConnect
  reason = noAvailableHosts
  errorReply = nil
}
```

This could just be Xcode playing tricks on me, or ironically me not setting up the project properly given I wrote the installation instructions.  Is anyone else experiencing this?

**Comment by ahmetws** [comment]
Did you try to remove the Xcode project and run `vapor xcode` again? It may solve your problem.

**Comment by jstashh** [comment]
@ahmetws Yes, Xcode just got in a bad mood... classic. It works fine
