### ISSUE TITLE
Add info text for empty speaker page

### ISSUE THREAD

**Issue by ahmetws** [ahmetws/swifttube#7]
Some speakers don't have videos. (http://www.swifttube.co/speaker/ahmetws)

An info description would be nice for the visitors to understand there is no video for these speakers, yet.

"There is no video for {speaker.fullname} right now. We are working hard to add new videos. They will be here soon."

**Comment by jstashh** [comment]
Would love to help with this. Have downloaded the repo and tried to run the project locally but getting `Assertion failed: URL can not be nil`. Any tips on getting up and running?

**Comment by ahmetws** [comment]
Great @wstompearson 👍

I think the problem is you don't have the DB_URL environment variable on Swifttube schema. Could you please check this and confirm you have the parameter in Swifttube schema?

**Comment by jstashh** [comment]
@ahmetws Cool thanks, I'm able to add the DB_URL env variable. What should it be set to?

**Comment by ahmetws** [comment]
@wstompearson Please try to run Swifttube schema and it should work as expected. If it doesn't, you can find the DB_URL and schema configuration in this pull request https://github.com/ahmetws/swifttube/pull/5/files
